name: Create Pull Request with gh CLI

on:
  push:
    branches:
      - feature/** # Trigger when changes are pushed to your feature branch

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false


      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub Actions
        run: |
          gh pr create \
            --base main \
            --head '${{ github.ref_name }}' \
            --title "Automated PR from feature branch" \
            --body "This pull request was created automatically by a GitHub Action."