name: Pull Request Action


permissions:
  contents: write
  issues: write
  checks: write
  actions: write
  packages: read
  pull-requests: write

on:
  push:
    branches:
      - feature/**
      
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Pull Request
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { repo, owner } = context.repo;
            const listPR = await github.rest.pulls.list({
              owner: owner,
              repo: repo,
              head: ${{github.ref_name}},
              base: 'dev',
              state: "open"
            });
            console.log(owner);
            if(list.data.length > 0){
              console.log('PR jรก existe para ${{github.ref_name}}');
            }else {
              const result = await github.rest.pulls.create({
                title: 'dev <- ${{github.ref_name}}',
                owner: owner,
                repo:  repo,
                head: '${{ github.ref_name }}',
                state: "open",
                base: 'dev',
                body: [
                  'This PR is auto-generated by',
                  '[actions/github-script](https://github.com/actions/github-script).'
                ].join('\n')
              });
              github.rest.issues.addLabels({
                owner,
                repo,
                issue_number: result.data.number,
                labels: ['feature', 'automated pr']
              });
            }