name: Semantic Release

permissions:
  contents: write
  issues: write
  checks: write
  actions: write
  packages: read
  pull-requests: write

on:
  pull_request:
    types: closed
    branches: [dev]


jobs:
  semantic-release:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    name: Semantic Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      #- name: Prepare prerelease semantic
        #if: github.ref != 'refs/heads/main'
        #run: mv .releaserc.prerelease.yaml .releaserc.yaml

      - name: Create Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        with:
            dry_run: true
            #semantic_version: 19
            #extra_plugin: |
            #    @semantic-release/commit-analyzer
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Print next version
        run: |
            echo "Next version: ${{ steps.semantic.outputs.new_release_version }}"
  #create-pull-request:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v4
  #      with:
  #        fetch-depth: 0

      - name: Create Release
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.git.createRef({
              owner: owner,
              repo:  repo,
              ref: "refs/heads/release-${{steps.semantic.outputs.new_release_version}}",
              sha: result.data.commit.sha
              });