name: Semantic Release

on:
  workflow_call:
    inputs:
      in-branch:
        description: 'Branch origem do PR'
        default: dev
        required: false
        type: string
      ou-branch:
        description: 'Branch destino do PR'
        default: main
        required: false
        type: string


jobs:
  semantic-release:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    name: Semantic Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      #- name: Prepare prerelease semantic
        #if: github.ref != 'refs/heads/main'
        #run: mv .releaserc.prerelease.yaml .releaserc.yaml

      - name: Create Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        with:
            dry_run: true
            #semantic_version: 19
            #extra_plugin: |
            #    @semantic-release/commit-analyzer
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Print next version
        run: |
            echo "Next version: ${{ steps.semantic.outputs.new_release_version }}"
  #create-pull-request:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v4
  #      with:
  #        fetch-depth: 0

      - name: Create Release
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: "Nova release release/${{semantic.outputs.new_release_version}} <- ${{inputs.in-branch}}",
              owner: owner,
              repo:  repo,
              head: ${{inputs.in-branch}},
              base: ${{inputs.ou-branch}},
              body: [
                'This PR is auto-generated by',
                '[actions/github-script](https://github.com/actions/github-script).'
              ].join('\n')
            });
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
              labels: ['release', 'automated pr']
            });